# MANAGED by EpiAwarePackageTools.scaffold — do not edit by hand.
# EPIAWARE_MANAGED_PAGES
#
# The docs navigation tree, regenerated on every `scaffold`/`update`. Group
# labels, ordering and placement are the kit's; a package adds its own
# content through `docs/docs_config.jl` (PACKAGE_TUTORIALS, PACKAGE_SECTIONS,
# DEVELOPMENT_EXTEND_PAGE, GETTING_STARTED_FAQ) rather than editing this file
# — any edit made here is overwritten on the next sync (#170/#328/#354).
#
# The Extensions group is written from whatever `[extensions]` the package
# declares in Project.toml, one entry per extension pointing at a page under
# `docs/src/extensions/`; a build drops any entry whose page is missing.
#
# The Benchmarks entry is written with `benchmarks = true`, `ad = true`, or
# both: its own top-level nav group under `docs/src/benchmarks/`, never
# nested inside Tutorials. Performance over time appears with
# `benchmarks = true`, the AD-comparison report with `ad = true`. That report
# is the only AD page the kit writes; the AD-backends tutorial that used to sit
# under Getting started is retired, and its `ad-backends` anchor moved onto the
# report.
#
# Every entry must resolve to a page the package writes or `make.jl`
# generates. Docs about the kit itself live on the kit's own site (#194).

pages = [
    "Home" => "index.md",
    # Authored quickstart, distinct from the README-derived home page. The
    # optional FAQ and the package's own tutorials are both supplied from
    # docs_config.jl.
    "Getting started" => [
        "Overview" => "getting-started/index.md",
        "FAQ" => "getting-started/faq.md",
        "Installation" => "getting-started/installation.md",
    ],
    "API reference" => [
        "Public API" => "lib/public.md",
        "Internal API" => "lib/internals.md",
    ],
    "Extensions" => [
        "ChainRulesCore" => "extensions/chain-rules-core.md",
        "ChainRulesCore + LogExpFunctions + Mooncake" => "extensions/log-exp-functions-mooncake.md",
        "ChainRulesCore + Mooncake" => "extensions/mooncake.md",
        "Enzyme" => "extensions/enzyme.md",
        "ForwardDiff" => "extensions/forward-diff.md",
        "ReverseDiff" => "extensions/reverse-diff.md",
        "SurvivalDistributions" => "extensions/survival-distributions.md",
    ],
    "Benchmarks" => [
        "Performance over time" => "benchmarks/over-time.md",
        "AD comparison" =>
            "benchmarks/ad-comparison.md",
    ],
    "Tools" => [
        "Charter and status" => "tools/index.md",
        "Tape-strip: primal" => "tools/tape-strip.md",
        "User-facing opt-out: nondifferentiable" => "tools/nondifferentiable.md",
        "AD-safe evaluation hooks" => "tools/ad-safe-hooks.md",
        "Gamma-CDF derivative" => "tools/gamma-cdf.md",
        "Beta-CDF derivative" => "tools/beta-cdf.md",
        "xlogy/xlog1py Mooncake rules" => "tools/xlogy.md",
        "Streaming log-sum-exp: logsumexp_stream" => "tools/logsumexp-stream.md",
        "Reparameterisation trick: fixed_draw/ad_eltype" => "tools/reparameterisation.md",
    ],
    "Development" => [
        "Overview" => "developer/index.md",
        "Contributing" => "developer/contributing.md",
        "Adding a workaround" => "developer/adding-a-tool.md",
        "Release process" => "developer/release-process.md",
        "Developer FAQ" => "developer/faq.md",
    ],
    # Generated by `make.jl` from the repo's published GitHub releases; the
    # page degrades to a link when they cannot be fetched, so the entry is
    # always safe to keep.
    "Release notes" => "release-notes.md",
]
