# PACKAGE-OWNED — scaffold writes this once and never overwrites it.
# The docs navigation tree. Add tutorial / guide pages here as the package
# grows; `make.jl` reads `pages` from this file. The API reference and the
# README-derived home page are generated by `make.jl`.

pages = [
    "Home" => "index.md",
    # Authored quickstart (package-owned source pages, distinct from the
    # README-derived home page).
    "Getting started" => [
        "Overview" => "getting-started/index.md",
        "Installation" => "getting-started/installation.md",
        "FAQ" => "getting-started/faq.md"
    ],
    # One page per tool family, plus the charter page listing each entry's
    # upstream target and deletion condition.
    "Tools" => [
        "Charter and status" => "tools/index.md",
        "Tape-strip: primal" => "tools/tape-strip.md",
        "AD-safe evaluation hooks" => "tools/ad-safe-hooks.md",
        "Gamma-CDF derivative" => "tools/gamma-cdf.md"
    ],
    "API reference" => [
        "Public API" => "lib/public.md",
        "Internal API" => "lib/internals.md"
    ],
    # Performance over time (the AirspeedVelocity history, `benchmarks.md`)
    # and the AD backend comparison (an executable Literate tutorial under
    # `getting-started/tutorials`, mostly a benchmark report despite living
    # there) — grouped together as the two benchmark views (#28).
    "Benchmarks" => [
        "Performance over time" => "benchmarks.md",
        "AD comparison" => "getting-started/tutorials/ad-backends.md"
    ],
    "Development" => [
        "Overview" => "developer/index.md",
        "Contributing" => "developer/contributing.md",
        "Adding a workaround" => "developer/adding-a-tool.md",
        "Release process" => "developer/release-process.md",
        "Developer FAQ" => "developer/faq.md"
    ]
]
